# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21a675adf48416707dd4aaef007be030b3a0743492308498fc305c97f632c571b2ea47718728d917ea423b4060b195aa960e2b87ab110684732e630d89ec7dc3

test:
  secret_key_base: 827335abd4957118a7b1e088c79db342c168da15a2da535ce00c5ff333401a26357fae67a98ccb04db3923424561020e8f05b95f4af50692987ad92144e5ab80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
